server:
  port: 8050

spring:
    application: 
       name: gateway-zuul
eureka: 
   client: 
      service-url: 
         deufaltZone: http://user:password123@localhost:8761/eurekaa
zuul:
   ignoredServides: '*'
   routes:
      app-consumer-hystrix:
         path: /user/**
         serviceId: consumer-hystrix
      app-sidecar:
         path: /sidecar/**
         serviceId: sidecar
feign:
  hystrix:
    enabled: false
logging:
  level: 
   root: INFO