security: 
   basic: 
      enabled: true
   user: 
      name: user
      password: password123

server:
  port: 8761

spring:
    application: 
       name: provider-user
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/testboot?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
        username: root
        password: '123456'

eureka: 
   client: 
      register-with-eureka: false
      fetch-registry: false
      service-url: 
         deufaltZone: http://user:password123@localhost:8761/eureka

mybatis:
  typeAliasesPackage: cn.test.springboot.pojo
  mapperLocations: classpath:mapper/*.xml

logging:
  level: 
   com.tedu.mapper: debug